### ISSUE TITLE
Ability to remove files from IPFS or stop propagating

### ISSUE THREAD

**Issue by svetlanama** [aragon/aragon-react-boilerplate#54]
Hi , 

If Is there a possibility to remove files from ipfs, after I made publishing + propagating?
```
aragon apm publish major "--environment" "staging"
npx aragon ipfs propagate <hash>

```

I noticed that the garbage collector didn't remove them, after 48 hrs.

Or maybe there is some way to update files using the same hash?
Thanks.

**Comment by sohkai** [comment]
You won't be able to update the files and keep the same hash, that's just not how hash functions work.

You may want to look into [`ipfs files rm`](https://docs.ipfs.io/reference/api/cli/#ipfs-files-rm) or [`ipfs pin rm`](https://docs.ipfs.io/reference/api/cli/#ipfs-pin-rm).

**Comment by svetlanama** [comment]
@sohkai  thank you for the explanation,

Yeah, I did this already ``` ipfs files rm```  and   ```ipfs pin rm```
Wonder if there is some way in the network? Or the files will be cleaned by the garbage collector in case nobody touches them, even they were propagated? Or in case they were **propagated** there is **no chance to be removed**?

**Comment by sohkai** [comment]
Perhaps @0x6431346e may have some more insight, but whether the file is propagated or not should not influence if they should live in your system (on `pin` should do that).

Worst case you can delete those files manually by going to your ipfs db and removing the hashes 🤷‍♂.

**Comment by 0x6431346e** [comment]
Hi @svetlanama, you cannot remove files from the network. Why do you want to remove the published app? Is it supposed to be private?

That being said, even if you propagate a file, there is no guarantee that the public gateways that are being queried will not remove it after some time. (most likely, they will)

The garbage collector did not remove the files locally, because they were pinned. (AFAIK, `ipfs pin rm` unpins & removes them so that's the only command you need)

**Comment by svetlanama** [comment]
Hi @0x6431346e , 

Yes ```ipfs pin rm``` helped and files were removed by the garbage collector after some time. 

Thank you!
